# Generated by Django 6.0.2 on 2026-02-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='last_security_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='security_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='agent',
            name='tasks_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='tasks_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='total_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agent',
            name='uptime_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
